version: "3"
services: 
    lobsterdb:
        image: mongo
        container_name: lobsterdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
          - demo-network

    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #       - 8081:8081
    #     depends_on:
    #       - lobsterdb
    #     networks:
    #       - demo-network

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        ports:
            - 9200:9200
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
            - discovery.type=single-node
        networks:
            - demo-network

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.9.1
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        environment:
            elasticsearch.url: "http://elasticsearch:9200"
            elasticsearch.hosts: "http://elasticsearch:9200"
            ElasticConfiguration.Uri: "http://elasticsearch:9200"
        networks:
            - demo-network

    lobsterapi:
        image: lobsterapi
        build:
            context: ./lobsterapi
            dockerfile: WebApi/Dockerfile
        container_name: lobsterapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://lobsterdb:27017"
        depends_on:
            - lobsterdb
        ports:
            - "27000:80"
        networks:
          - demo-network

    clientsvc:
        image: lobsterweb
        build:
            context: ./lobsterweb
            dockerfile: Dockerfile
        ports: 
            - 28000:80
        networks:
            - demo-network
    
networks:
  demo-network:
    driver: bridge

volumes:
  mongo_data:
  elasticsearch-data: