version: "3"
services: 
    catalogdb:
        image: mongo
        container_name: catalogdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./database/mongodata:/data/db
        networks:
          - demo-network

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        depends_on:
          - catalogdb
        networks:
          - demo-network
    # websvc:
    #     image: lobsterapi
    #     build:
    #         context: ./lobsterapi/webapi
    #         dockerfile: Dockerfile
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Development
    #         - "DatabaseSettings:ConnectionString=mongodb://mongo:27017"
    #     depends_on:
    #         - mongo
    #     ports: 
    #         - 27000:80
    #     networks:
    #         - demo-network
    catalogapi:
        image: catalogapi
        build:
            context: .
            dockerfile: Catalog/Catalog.API/Dockerfile
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        ports:
            - "8000:80"
        networks:
          - demo-network
    clientsvc:
        image: lobsterweb
        build:
            context: ./lobsterweb
            dockerfile: Dockerfile
        ports: 
            - 28000:80
        networks:
            - demo-network
    
networks:
  demo-network:
    driver: bridge

# volumes:
#   mongo_data: