version: "3"
services: 
    lobsterdb:
        image: mongo
        container_name: lobsterdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./database/mongodata:/data/db
        networks:
          - demo-network

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        depends_on:
          - lobsterdb
        networks:
          - demo-network

    lobsterapi:
        image: lobsterapi
        build:
            context: ./lobsterapi
            dockerfile: WebApi/Dockerfile
        container_name: lobsterapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://lobsterdb:27017"
        depends_on:
            - lobsterdb
        ports:
            - "8000:80"
        networks:
          - demo-network

    clientsvc:
        image: lobsterweb
        build:
            context: ./lobsterweb
            dockerfile: Dockerfile
        ports: 
            - 28000:80
        networks:
            - demo-network
    
networks:
  demo-network:
    driver: bridge

# volumes:
#   mongo_data: not using this since mapping to repo folder